# Для работы телеграм-бота вставьте чат-id, при необходимости замените Токен
telegram:
  TOKEN: "6992030569:AAEMhDEOee66IsjvbQlVg_BF6w1s_GmtKu8"
  chat_id: "YOUR_CHAT_ID"
# Видео (поставьте 0 для камеры или путь до видео)
video:
  path: './video.mp4'