name: Lint Code Base

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc dvc-gdrive flake8 numpy opencv-python-headless pytest requests wget

    - name: Install DVC with GDrive support
      run: pip install 'dvc[gdrive]'

    - name: Setup DVC
      uses: iterative/setup-dvc@v1

#    - name: DVC pull
#      env:
#        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
#        run: |
#          dvc pull

    - name: Get test video
      run: |
        wget https://drive.google.com/file/d/1Bv8pKIf10KoDqw_QTOEQjeJPV0scNpLy/view?usp=sharing

    - name: Lint with flake8
      run: |
        # ignore 'Loop 32' is too complex and 'line too long'
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --ignore=C901,E402,E501 --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --ignore=C901,E402,E501 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics    

    - name: Test with pytest
      run: |
        pytest tests/

    - name: Test with unittest
      run: |
        python -m unittest discover -s tests
